{% extends bento_base_template %}
{% block SETUP_BENTO_COMPONENTS %}
LABEL org.opencontainers.image.source="https://github.com/bentoml/OCR-as-a-Service"
{{ super() }}
RUN pip install 'git+https://github.com/facebookresearch/detectron2.git'
{% endblock %}
